USE [ProjectManagementDb]
GO

/****** Object:  Table [dbo].[Departement]    Script Date: 10/1/2023 12:29:10 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Departement](
	[dep_id] [int] IDENTITY(1,1) NOT NULL,
	[dep_name] [nvarchar](100) NOT NULL,
	[dep_head_id] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[dep_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[dep_name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Departement]  WITH CHECK ADD  CONSTRAINT [DepHead] FOREIGN KEY([dep_head_id])
REFERENCES [dbo].[UserAcc] ([user_id])
GO

ALTER TABLE [dbo].[Departement] CHECK CONSTRAINT [DepHead]
GO

